language: php
php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  fast_finish: true

before_script:
  - composer install

script:
  - php vendor/bin/php-cs-fixer fix --dry-run --diff
  - php vendor/bin/phpstan.phar analyse -c phpstan.neon lib tests
  - php vendor/bin/phpunit --configuration tests/phpunit.xml
